### ISSUE TITLE
Feature Request: Add `--wait` option to `release deploy`

### ISSUE THREAD

**Issue by cdhunt** [OctopusDeploy/cli#153]
It would be convenient to not have to capture the output of `release deploy` and then call `task wait`.

**Comment by jbristowe** [comment]
Hey @cdhunt! :wave: Thanks for submitting this issue. This is by-design.

We have designed this command is to support multiple environments and tenants. This poses a challenge to determine if/when to wait. Since we target the Executions API, which returns a task ID, we decided that the best path forward was to provide users with the ability to wait on any one of these tasks. This gives you far more control in an automation context.

Furthermore, it should be stated that task completion does not imply a successful deployment; rather, it lets the user know that a task has completed in Octopus. This means that a task may complete but the deployment may be unsuccessful (i.e. error). Again, in order to provide control back to users, we designed the CLI to operate in this manner.

**Comment by cdhunt** [comment]
Thanks for the explanation. Makes sense.
