### ISSUE TITLE
No way to disable prompting for creating projects or project group

### ISSUE THREAD

**Issue by kierenj** [OctopusDeploy/cli#313]
I'm trying to automate creation of project groups and projects.

`octopus project-group create --name "$projectGroup"` prompts for a description, I don't want it to.

`--no-prompt` yields `panic: space must be specified when not running interactively; please set the OCTOPUS_SPACE environment variable or specify --space on the command line`

`-d ""` yields `flag needs an argument: 'd' in -d`

I also don't want it to prompt for "Config as code", but there's no commandline option for that. `--no-prompt` again gives a crash

## Versions

**cli**: 2.1.0

**Octopus Server**: hosted on octopus.app

**Comment by benPearce1** [comment]
@kierenj Did you try specifying the space via `--space` or `-s` or the `OCTOPUS_SPACE` environment variable?

I tested the `project-create` command and got the same output that you did. This is expected behaviour.

```
❯ ./octopus project-group create -s default -n test-group-1 --no-prompt

Successfully created project group test-group-1.
View this project group on Octopus Deploy: http://localhost:8066/app#/Spaces-1/projectGroups/ProjectGroups-402
```

I also tested the same for `project create`, no errors  when specifying the space on the command line
```
❯ ./octopus project create -s default --name test-group-2 -d "" --lifecycle "Default lifecycle" --group test-group-1 --no-prompt

Successfully created project 'test-group-2' (test-group-2), with lifecycle 'Default lifecycle' in project group 'test-group-1'.
View this project on Octopus Deploy: http://localhost:8066/app#/Spaces-1/projects/Projects-1041
```

The reason you see a difference between `--no-prompt` and interactive mode is that you will be prompted for the space in interactive mode. `--no-prompt` means there are no prompts and it just fails if the command is invalid.
